apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ Values.appName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ Values.appName }}
          servicePort: {{ .Values.service.port }}